import { createLineaOreClientViewProps } from "./lineaOreClientViewProps";
import type { useLineaOreClientBaseState } from "../hooks/useLineaOreClientBaseState";
import type { useLineaOreHubRuntime } from "../hooks/useLineaOreHubRuntime";
import type { useLineaOreWalletRuntime } from "../hooks/useLineaOreWalletRuntime";
import type { usePageAncillaryData } from "../hooks/usePageAncillaryData";
import type { useRebate } from "../hooks/useRebate";

interface BuildLineaOreClientRuntimeViewPropsOptions {
  baseState: ReturnType<typeof useLineaOreClientBaseState>;
  ancillaryState: ReturnType<typeof usePageAncillaryData>;
  walletRuntime: ReturnType<typeof useLineaOreWalletRuntime>;
  hubRuntime: ReturnType<typeof useLineaOreHubRuntime>;
  rebateState: Pick<ReturnType<typeof useRebate>, "rebateInfo" | "isClaiming" | "claimRebates">;
}

export function buildLineaOreClientRuntimeViewProps({
  baseState,
  ancillaryState,
  walletRuntime,
  hubRuntime,
  rebateState,
}: BuildLineaOreClientRuntimeViewPropsOptions) {
  const { shell, gameData, wallet, motion, sound, normalizedEmbeddedAddress, chatWalletAddress, coldBootDefaults } =
    baseState;
  const {
    deposits,
    depositsLoading,
    totalDeposited,
    depositsError,
    fetchDeposits,
    refreshDeposits,
    walletTransfers,
    walletTransfersLoading,
    fetchWalletTransfers,
    deepScanWins,
    deepScanScanning,
    deepScanClaiming,
    deepScanProgress,
    deepScan,
    deepScanStop,
    deepClaimOne,
    claimAllDeep,
    leaderboardsData,
    leaderboardsLoading,
    leaderboardsError,
    leaderboardsRefetch,
    recentWins,
    jackpotHistory,
    jackpotHistoryLoading,
    jackpotHistoryError,
    refreshJackpotHistory,
  } = ancillaryState;

  return createLineaOreClientViewProps({
    activeTab: shell.activeTab,
    actualCurrentEpoch: gameData.actualCurrentEpoch,
    address: gameData.address,
    autoMineProgress: hubRuntime.autoMineProgress,
    backupGateVersion: shell.backupGateVersion,
    balanceWarningDismissed: hubRuntime.balanceWarningDismissed,
    chatOpen: shell.chatOpen,
    claimAll: hubRuntime.claimAll,
    claimAllDeep,
    claimRebates: rebateState.claimRebates,
    claimReward: hubRuntime.claimReward,
    closeWalletSettings: shell.closeWalletSettings,
    coldBootDefaults,
    createEmbeddedWallet: wallet.createEmbeddedWallet,
    deepClaimOne,
    deepScan,
    deepScanClaiming,
    deepScanProgress,
    deepScanScanning,
    deepScanStop,
    deepScanWins,
    depositEthAmount: walletRuntime.depositEthAmount,
    depositTokenAmount: walletRuntime.depositTokenAmount,
    deposits,
    depositsError,
    depositsLoading,
    dismissBalanceWarning: hubRuntime.dismissBalanceWarning,
    embeddedAddressCopied: walletRuntime.embeddedAddressCopied,
    embeddedWalletAddress: wallet.embeddedWalletAddress,
    embeddedWalletSyncing: wallet.embeddedWalletSyncing,
    epochDurationChange: gameData.epochDurationChange,
    exportEmbeddedWallet: wallet.exportEmbeddedWallet,
    externalWalletAddress: wallet.externalWalletAddress,
    fetchDeposits,
    fetchWalletTransfers,
    formattedLineaBalance: gameData.formattedLineaBalance,
    formattedPrivyBalance: walletRuntime.formattedPrivyBalance,
    formattedPrivyEthBalance: walletRuntime.formattedPrivyEthBalance,
    gridDisplayEpoch: gameData.gridDisplayEpoch,
    gridSelectedTiles: hubRuntime.gridSelectedTiles,
    handleAutoMineWithGuard: hubRuntime.handleAutoMineWithGuard,
    handleBackupConfirm: shell.handleBackupConfirm,
    handleCopyEmbeddedAddress: walletRuntime.handleCopyEmbeddedAddress,
    handleDepositEthToEmbedded: walletRuntime.handleDepositEthToEmbedded,
    handleDepositTokenToEmbedded: walletRuntime.handleDepositTokenToEmbedded,
    handleManualMineWithGuard: hubRuntime.handleManualMineWithGuard,
    handleRepeatLastBet: hubRuntime.handleRepeatLastBet,
    handleTabChange: shell.handleTabChange,
    handleWithdrawEthToExternal: walletRuntime.handleWithdrawEthToExternal,
    handleWithdrawToExternal: walletRuntime.handleWithdrawToExternal,
    hasMyWinningBet: gameData.hasMyWinningBet,
    headerEthLoading: walletRuntime.headerEthLoading,
    headerLineaBalance: walletRuntime.headerLineaBalance,
    headerLineaLoading: walletRuntime.headerLineaLoading,
    historyLoading: gameData.historyLoading,
    historyRefreshing: gameData.historyRefreshing,
    historyViewData: gameData.historyViewData,
    isAnalyzing: hubRuntime.isAnalyzing,
    isAutoMining: hubRuntime.isAutoMining,
    isCancellingPendingTx: walletRuntime.isCancellingPendingTx,
    isClaiming: hubRuntime.isClaiming,
    isClaimingRebate: rebateState.isClaiming,
    isDailyJackpot: gameData.isDailyJackpot,
    isDeepScanning: hubRuntime.isDeepScanning,
    isDepositingEth: walletRuntime.isDepositingEth,
    isDepositingToken: walletRuntime.isDepositingToken,
    isPageVisible: shell.isPageVisible,
    isPending: hubRuntime.isPending,
    isRefreshingPendingTx: walletRuntime.isRefreshingPendingTx,
    isRevealing: gameData.isRevealing,
    isScanning: hubRuntime.isScanning,
    isWalletSettingsOpen: shell.isWalletSettingsOpen,
    isWeeklyJackpot: gameData.isWeeklyJackpot,
    isWithdrawing: walletRuntime.isWithdrawing,
    isWithdrawingEth: walletRuntime.isWithdrawingEth,
    jackpotAmount: gameData.jackpotAmount,
    jackpotHistory,
    jackpotHistoryError,
    jackpotHistoryLoading,
    jackpotInfo: gameData.jackpotInfo,
    lastBet: hubRuntime.lastBet,
    leaderboardsData,
    leaderboardsError,
    leaderboardsLoading,
    leaderboardsRefetch,
    liveStateReady: gameData.liveStateReady,
    timerReady: gameData.timerReady,
    lowEthBalance: hubRuntime.lowEthBalance,
    lowTokenBalance: hubRuntime.lowTokenBalance,
    chatWalletAddress,
    normalizedEmbeddedAddress,
    onChatOpenChange: shell.setChatOpen,
    openWalletSettings: shell.openWalletSettings,
    pendingTransactionStatus: walletRuntime.pendingTransactionStatus,
    eip7702Diagnostic: wallet.eip7702Diagnostic,
    onRunEip7702Diagnostic: wallet.runEip7702Diagnostic,
    onRunEip7702SendDiagnostic: wallet.runEip7702SendDiagnostic,
    rebateInfo: rebateState.rebateInfo,
    recentWins,
    reducedMotion: motion.reducedMotion,
    refreshDeposits,
    refreshJackpotHistory,
    refreshPendingTransactionStatus: walletRuntime.refreshPendingTransactionStatus,
    rolloverAmount: gameData.rolloverAmount,
    runningParams: hubRuntime.runningParams,
    scanRewards: hubRuntime.scanRewards,
    selectedTilesCount: hubRuntime.selectedTiles.length,
    setDepositEthAmount: walletRuntime.setDepositEthAmount,
    setDepositTokenAmount: walletRuntime.setDepositTokenAmount,
    setReducedMotion: motion.setReducedMotion,
    setSoundEnabled: sound.setSoundEnabled,
    setWithdrawAmount: walletRuntime.setWithdrawAmount,
    setWithdrawEthAmount: walletRuntime.setWithdrawEthAmount,
    showSelectionOnGrid: hubRuntime.showSelectionOnGrid,
    soundMuted: sound.muted,
    soundSettings: sound.soundSettings,
    stableTileClick: hubRuntime.stableTileClick,
    tileViewData: gameData.tileViewData,
    timeLeft: gameData.timeLeft,
    toggleSoundMute: sound.toggleMute,
    totalDeposited,
    unclaimedWins: hubRuntime.unclaimedWins,
    visibleHotTiles: shell.visibleHotTiles,
    visualEpoch: gameData.visualEpoch,
    walletTransfers,
    walletTransfersLoading,
    winningTileId: gameData.winningTileId,
    withdrawAmount: walletRuntime.withdrawAmount,
    withdrawEthAmount: walletRuntime.withdrawEthAmount,
    cancelPendingTransaction: walletRuntime.cancelPendingTransaction,
  });
}
