const PROJECT_ROOT = process.env.PROJECT_ROOT || "/root/LORE";
const PM2_LOG_DIR = process.env.PM2_LOG_DIR || "/root/.pm2/logs";

module.exports = {
  apps: [
    {
      name: "lore-site",
      cwd: PROJECT_ROOT,
      script: "npm",
      args: "run start",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 20,
      restart_delay: 3000,
      out_file: `${PM2_LOG_DIR}/lore-site-out.log`,
      error_file: `${PM2_LOG_DIR}/lore-site-error.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "lore-bot",
      cwd: PROJECT_ROOT,
      script: "npm",
      args: "run bot",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 50,
      restart_delay: 3000,
      out_file: `${PM2_LOG_DIR}/lore-bot-out.log`,
      error_file: `${PM2_LOG_DIR}/lore-bot-error.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "lore-indexer",
      cwd: PROJECT_ROOT,
      script: "npm",
      args: "run indexer",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 50,
      restart_delay: 3000,
      stop_exit_codes: [78],
      out_file: `${PM2_LOG_DIR}/lore-indexer-out.log`,
      error_file: `${PM2_LOG_DIR}/lore-indexer-error.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "lore-monitor",
      cwd: PROJECT_ROOT,
      script: "npm",
      args: "run monitor:runtime",
      env: {
        NODE_ENV: "production",
      },
      autorestart: true,
      max_restarts: 50,
      restart_delay: 10000,
      out_file: `${PM2_LOG_DIR}/lore-monitor-out.log`,
      error_file: `${PM2_LOG_DIR}/lore-monitor-error.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "lore-backup",
      cwd: PROJECT_ROOT,
      script: "npm",
      args: "run db:backup",
      env: {
        NODE_ENV: "production",
      },
      autorestart: false,
      cron_restart: process.env.LORE_BACKUP_CRON || "0 3 * * *",
      out_file: `${PM2_LOG_DIR}/lore-backup-out.log`,
      error_file: `${PM2_LOG_DIR}/lore-backup-error.log`,
      merge_logs: true,
      time: true,
    },
    {
      name: "lore-chain-audit",
      cwd: PROJECT_ROOT,
      script: "npm",
      args: "run audit:chain-indexer",
      env: {
        NODE_ENV: "production",
      },
      autorestart: false,
      cron_restart: process.env.CHAIN_INDEXER_AUDIT_CRON || "*/30 * * * *",
      out_file: `${PM2_LOG_DIR}/lore-chain-audit-out.log`,
      error_file: `${PM2_LOG_DIR}/lore-chain-audit-error.log`,
      merge_logs: true,
      time: true,
    },
  ],
};
