"use client";

import { useMemo } from "react";
import { useAccount, usePublicClient, useWriteContract } from "wagmi";
import { APP_CHAIN_ID } from "../lib/constants";
import { useMiningRuntimeState } from "./useMiningRuntimeState";
import { useMiningOrchestration } from "./useMiningOrchestration";
import type { UseMiningOptions } from "./useMining.types";

export function useMining({
  refetchAllowance,
  refetchTileData,
  refetchUserBets,
  refetchEpoch,
  refetchGridEpochData,
  preferredAddress,
  ensurePreferredWallet,
  sendTransactionSilent,
  sendTransaction7702,
  signEip7702Delegation,
  eip7702,
  refreshSession,
  onAutoMineBetConfirmed,
  onNotify,
}: UseMiningOptions) {
  const { address } = useAccount();
  const publicClient = usePublicClient({ chainId: APP_CHAIN_ID });
  const { writeContractAsync } = useWriteContract();

  const {
    isPending,
    setIsPending,
    autoMinePhase,
    isAutoMining,
    setIsAutoMining,
    autoMineProgress,
    setAutoMineProgress,
    runningParams,
    setRunningParams,
    activateAutoMineUi,
    deactivateAutoMineUi,
    setAutoMinePhase,
    hasPreferredActor,
    getActorAddress,
    getPreferredActorAddress,
    autoMineRef,
    autoResumeRequestedRef,
    restoreAttemptedRef,
    sessionExpiredErrorRef,
    tokenGetterWarningShownRef,
    pendingApproveRef,
    pendingBetRef,
    publicClientRef,
    silentSendRef,
    silentSend7702Ref,
    signEip7702DelegationRef,
    eip7702Ref,
    refreshSessionRef,
    writeContractAsyncRef,
    ensurePreferredWalletRef,
    refetchAllowanceRef,
    refetchTileDataRef,
    refetchUserBetsRef,
    refetchEpochRef,
    refetchGridEpochDataRef,
    onAutoMineBetConfirmedRef,
    notifyRef,
  } = useMiningRuntimeState({
    address,
    publicClient,
    writeContractAsync: (args: unknown) => writeContractAsync(args as never),
    preferredAddress,
    ensurePreferredWallet,
    sendTransactionSilent,
    sendTransaction7702,
    signEip7702Delegation,
    eip7702,
    refreshSession,
    onAutoMineBetConfirmed,
    onNotify,
    refetchAllowance,
    refetchTileData,
    refetchUserBets,
    refetchEpoch,
    refetchGridEpochData,
  });

  const {
    selectedTiles,
    selectedTilesEpoch,
    handleManualMine,
    handleDirectMine,
    handleAutoMineToggle,
    handleTileClick,
    setTiles,
  } = useMiningOrchestration({
    publicClient,
    getActorAddress,
    getPreferredActorAddress,
    hasPreferredActor,
    autoMineRef,
    autoResumeRequestedRef,
    restoreAttemptedRef,
    sessionExpiredErrorRef,
    tokenGetterWarningShownRef,
    pendingApproveRef,
    pendingBetRef,
    publicClientRef,
    silentSendRef,
    silentSend7702Ref,
    signEip7702DelegationRef,
    eip7702Ref,
    refreshSessionRef,
    writeContractAsyncRef,
    ensurePreferredWalletRef,
    refetchAllowanceRef,
    refetchTileDataRef,
    refetchUserBetsRef,
    refetchEpochRef,
    refetchGridEpochDataRef,
    onAutoMineBetConfirmedRef,
    notifyRef,
    autoMinePhase,
    isAutoMining,
    setIsPending,
    setIsAutoMining,
    setAutoMineProgress,
    setRunningParams,
    activateAutoMineUi,
    deactivateAutoMineUi,
    setAutoMinePhase,
  });

  return useMemo(
    () => ({
      isPending,
      selectedTiles,
      selectedTilesEpoch,
      autoMinePhase,
      isAutoMining,
      autoMineProgress,
      runningParams,
      handleManualMine,
      handleDirectMine,
      handleAutoMineToggle,
      handleTileClick,
      setTiles,
    }),
    [
      isPending,
      selectedTiles,
      selectedTilesEpoch,
      autoMinePhase,
      isAutoMining,
      autoMineProgress,
      runningParams,
      handleManualMine,
      handleDirectMine,
      handleAutoMineToggle,
      handleTileClick,
      setTiles,
    ],
  );
}
